//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATOS.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string id { get; set; }
        public string idOrder { get; set; }
        public string idProduct { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> price { get; set; }
        public string details { get; set; }
        public Nullable<byte> state { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
